# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4107431c0f97b4c0fadcd2230e7e1466215c903222b54d60cfdf57152e39edbd90b85d0fe92072592f2fe2917fb1b422a99d8ad1ad74bed2b4d4514506a73638

test:
  secret_key_base: 21ffe459b0ffb3ffa2cfe561d5b5aac97cb35ad03ff90d27129ce5c8bb3873468bd8317c12294b9bfa1dcfe59c4b0e12e797756d280e797cab893e16f1a44f30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
